trigger:
  branches:
    include:
      - uat
pr: none
pool:
  vmImage: ubuntu-latest

stages:
  - stage:  Deploy_to_UAT_Databricks
    displayName: Deploy to UAT  Databricks
    jobs:
      - job:  Deploy_to_UAT_Databricks
        displayName:  Deploy to UAT  Databricks   
        steps:
        - checkout: self
          fetchDepth: 0
          displayName: Checkout repository (full history)

        - script: |
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
            databricks version
          displayName: Install Databricks CLI

        - script: |
            if [ "$(Build.SourceBranchName)" == "uat" ]; then
              echo "copied databricks.yml to 'uat' branch root dir"
              cp env_bundle_files/uat/databricks.yml .
            else
              echo "❌ No matching target branch"
            fi
          displayName: Set DAB config based on branch

        - script: |
            databricks bundle validate -t $(DATABRICKS_BUNDLE_ENV)
          displayName: Validate Databricks Bundle
          env:
            DATABRICKS_HOST:  $(DATABRICKS_HOST)
            DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
            DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
        - script: |
            databricks bundle deploy -t $(DATABRICKS_BUNDLE_ENV) --auto-approve --force-lock
          displayName: Apply Databricks Bundle
          env:
            DATABRICKS_HOST:  $(DATABRICKS_HOST)
            DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
            DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
