trigger:
  branches:
    include:
      - develop
pr: none

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Init
    displayName: Initialization Stage
    jobs:
      - job: DummyJob
        displayName: Dummy Job
        steps:
          - script: |
              echo "Pipeline started successfully - Build ID: $(Build.BuildNumber)"
            displayName: Dummy Task
          - script: |
              if [ "$(Build.SourceBranchName)" == "develop" ]; then
                cp env_bundle_files/develop/databricks.yml .
                echo "copied databricks.yml to 'develop' branch root dir"
                
              else
                echo "❌ No matching target branch"
              fi
            displayName: Set DAB config based on branch 
